CREATE DATABASE IF NOT EXISTS ocm_webcompile DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS ocm_webcompile.site_section (
	Section_ID TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	Section_Title VARCHAR(100) NOT NULL,
	Page_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (Section_ID),
	UNIQUE KEY UN_Section_Title (Section_Title)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ocm_webcompile.site_page (
	Page_ID TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	Page_Title VARCHAR(100) NOT NULL,
	Page_Path VARCHAR(200) NOT NULL,
	Page_Name VARCHAR(100) NOT NULL,
	Page_MetaDesc VARCHAR(200) NOT NULL,
	Page_MetaKey VARCHAR(200) NOT NULL,
	Page_Content TEXT,
	Section_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (Page_ID),
	UNIQUE KEY UN_Page_Title (Page_Title),
	UNIQUE KEY UN_Page_Path (Page_Path),
	UNIQUE KEY UN_Page_Name (Page_Name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ocm_webcompile.site_nav (
	Nav_ID TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	Nav_Title VARCHAR(100) NOT NULL,
	Section_ID TINYINT(1) UNSIGNED NOT NULL,
	Page_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY (Nav_ID)
) ENGINE=InnoDB;






CREATE TABLE IF NOT EXISTS ocm_webcompile.default_meta (
	Meta_ID TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	Meta_Tag VARCHAR(50) NOT NULL,
	Meta_Value VARCHAR(100) NOT NULL,
	PRIMARY KEY (Meta_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ocm_webcompile.default_url (
	Url_ID TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	Url_Name VARCHAR(50) NOT NULL,
	Url_Value VARCHAR(100) NOT NULL,
	PRIMARY KEY (Url_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;









